### ISSUE TITLE
Video not show

### ISSUE THREAD

**Issue by raven2cz** [SamsungDForum/SmartViewSDKYouTubePlayer#1]
The connection of android app to TV Tizen is successful. The log on Tv shows connection, start or stop buttons works. The view is changes for thumbnail and video part. But the thumbnail and video parts missing. The video is not played. In the log there is no error message, nothing. It seems that the actual version of Tizen doesn't work with it. I don't know what can I activate to see more details about problem.

**Comment by RockingPrafull** [comment]
Please go through the README.md  of Android project to create youtube api key.
Under Required Modification : 
You must get Youtube API KEY to test this app.
refer to below url
Creating a YouTube API Key

: http://support.andromo.com/kb/common-questions/creating-a-youtube-api-key.

Thanks.
